<a href="https://colab.research.google.com/github/shipra-saxena/miniature-potato/blob/master/mushroom_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import svm

In [43]:
df=pd.read_csv('/content/mushrooms.csv')
df.shape


(8124, 23)

In [44]:
df

class cap-shape cap-surface  ... spore-print-color population habitat
0        p         x           s  ...                 k          s       u
1        e         x           s  ...                 n          n       g
2        e         b           s  ...                 n          n       m
3        p         x           y  ...                 k          s       u
4        e         x           s  ...                 n          a       g
...    ...       ...         ...  ...               ...        ...     ...
8119     e         k           s  ...                 b          c       l
8120     e         x           s  ...                 b          v       l
8121     e         f           s  ...                 b          c       l
8122     p         k           y  ...                 w          v       l
8123     e         x           s  ...                 o          c       l

[8124 rows x 23 columns]

In [45]:
df.describe()

class cap-shape cap-surface  ... spore-print-color population habitat
count   8124      8124        8124  ...              8124       8124    8124
unique     2         6           4  ...                 9          6       7
top        e         x           y  ...                 w          v       d
freq    4208      3656        3244  ...              2388       4040    3148

[4 rows x 23 columns]

In [46]:
df.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

One Hot Encoding

In [0]:
column_convert=set(df.columns)-set(['class'])
df_new=pd.concat([df,pd.get_dummies(df[column_convert],prefix=column_convert)],axis=1)

In [0]:
df1=pd.get_dummies(df)

In [49]:
df1.columns

Index(['class_e', 'class_p', 'cap-shape_b', 'cap-shape_c', 'cap-shape_f',
       'cap-shape_k', 'cap-shape_s', 'cap-shape_x', 'cap-surface_f',
       'cap-surface_g',
       ...
       'population_s', 'population_v', 'population_y', 'habitat_d',
       'habitat_g', 'habitat_l', 'habitat_m', 'habitat_p', 'habitat_u',
       'habitat_w'],
      dtype='object', length=119)

In [50]:
df_new

class cap-shape cap-surface  ... ring-type_l ring-type_n ring-type_p
0        p         x           s  ...           0           0           1
1        e         x           s  ...           0           0           1
2        e         b           s  ...           0           0           1
3        p         x           y  ...           0           0           1
4        e         x           s  ...           0           0           0
...    ...       ...         ...  ...         ...         ...         ...
8119     e         k           s  ...           0           0           1
8120     e         x           s  ...           0           0           1
8121     e         f           s  ...           0           0           1
8122     p         k           y  ...           0           0           0
8123     e         x           s  ...           0           0           1

[8124 rows x 140 columns]

In [0]:
df_new["class"].replace(["e", "p"], [1, 0], inplace= True)

In [52]:
df_new

class cap-shape cap-surface  ... ring-type_l ring-type_n ring-type_p
0         0         x           s  ...           0           0           1
1         1         x           s  ...           0           0           1
2         1         b           s  ...           0           0           1
3         0         x           y  ...           0           0           1
4         1         x           s  ...           0           0           0
...     ...       ...         ...  ...         ...         ...         ...
8119      1         k           s  ...           0           0           1
8120      1         x           s  ...           0           0           1
8121      1         f           s  ...           0           0           1
8122      0         k           y  ...           0           0           0
8123      1         x           s  ...           0           0           1

[8124 rows x 140 columns]

In [0]:
y=df_new['class']

In [0]:
df_final=df_new.drop(columns=df.columns)

In [55]:
df_final

gill-color_b  gill-color_e  ...  ring-type_n  ring-type_p
0                0             0  ...            0            1
1                0             0  ...            0            1
2                0             0  ...            0            1
3                0             0  ...            0            1
4                0             0  ...            0            0
...            ...           ...  ...          ...          ...
8119             0             0  ...            0            1
8120             0             0  ...            0            1
8121             0             0  ...            0            1
8122             1             0  ...            0            0
8123             0             0  ...            0            1

[8124 rows x 117 columns]

Corellation

In [0]:
x_train,x_test= train_test_split(df_final,random_state=1)
y_train,y_test=train_test_split(y,random_state=1)

In [115]:
y_train.value_counts()

1    3188
0    2905
Name: class, dtype: int64

In [116]:
y_test.value_counts()

1    1020
0    1011
Name: class, dtype: int64

Using Logistic regression

In [0]:
from sklearn.linear_model import LogisticRegression

In [133]:
model= LogisticRegression(random_state=1,solver='lbfgs')
model.fit(x_train,np.ravel(y_train))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred=model.predict(x_test)

In [0]:
lr_y_pred_proba = model1.predict_proba(x_test)[:, 1]
thresh = .5
lr_y_predict = [1 if value > thresh else 0 for value in lr_y_pred_proba]

In [136]:
lr_y_pred_proba

array([9.99999877e-01, 1.76645768e-05, 2.96506022e-05, ...,
       1.52389190e-05, 2.10474549e-06, 2.87270966e-07])

In [137]:
from sklearn.metrics import classification_report
from sklearn.metrics import *
print(accuracy_score(y_test,lr_y_predict))

0.9975381585425899


In [138]:
print(confusion_matrix(y_test,lr_y_predict))

[[1006    5]
 [   0 1020]]


Using SVM

In [124]:
model1=svm.SVC(probability=True)
model1.fit(x_train,np.ravel(y_train))

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=True, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred=model1.predict(x_test)

In [126]:
print(confusion_matrix(y_test,y_pred))

[[1005    6]
 [   0 1020]]


In [127]:
print(accuracy_score(y_test,y_pred))

0.9970457902511078


Using Random forest classifier

In [0]:
from sklearn.ensemble import RandomForestClassifier

In [129]:
model=RandomForestClassifier(n_estimators =  100, n_jobs=-1, random_state=1)
model.fit(x_train,np.ravel(y_train))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [0]:
y_pred=model.predict(x_test)

In [131]:
print(confusion_matrix(np.ravel(y_test),y_pred))

[[1011    0]
 [   0 1020]]


In [132]:
print(accuracy_score(np.ravel(y_test),y_pred))

1.0
